### ISSUE TITLE
copy-url compares the uri class against its type

### ISSUE THREAD

**Issue by lisp** [franzinc/uri#1]
good morning;

the copy-url parameter list[[1](http://github.com/franzinc/uri/blob/master/uri.cl#L116)] defaults to the intended class, but compares[[2](http://github.com/franzinc/uri/blob/master/uri.cl#L177)] with the type.

**Comment by OLDlayeratwork** [comment]
For some reason this fell in the cracks... we have filed an internal bug for this.  Yes, the `class-of` returns a class and using `(eq 'uri <class>)` will not have the intended effect.  Thanks.
